### PR TITLE
[ADD] add module base_compute_field_after_install

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Comment by bealdav** [comment]
génial ping @alexis-via

**Comment by rvalyi** [comment]
possible better naming: base_compute_field_deferred

**Comment by sebastienbeau** [comment]
hum, maybe defered will be confused, as people can think that all of the time computed field will be processed in background?
In my case it's only during the installation process to reduce the time to install a module, and then process it step by step (with intermediary commit)

**Comment by rvalyi** [comment]
@sebastienbeau makes sense, then let's keep the name as it works well too.

**Comment by bealdav** [comment]
@sebastienbeau please do not merge PR which breaks test of the branch.

Please try to never do it. Thanks

**Pull request merged**
