### PR TITLE
[IMP] base_jsonify: Allow fields aliasing in jsonify

### PR DESCRIPTION
**Pull request by lmignon**
@sebastienbeau As discussed yesterday, this PR allow you to specify an alias to use as key into the generated json

### CODE REVIEW

**Comment by sebastienbeau** [comment]
Youhou ! I like it. 
build fail (missing notify_email on partner creation) https://travis-ci.org/akretion/ak-odoo-incubator/jobs/238238320#L1169 can you fix it?
Thanks !!

**Comment by lmignon** [comment]
@sebastienbeau For sure I'll fix it. Nevertheless it's a strange error since base_jsonifiy doesn't depend of mail and even more the mali addon define a default value for this field...

**Comment by lmignon** [comment]
arghhh to fix travis, bas_jsonify should depend of mail..... it's a nonsense

**Comment by lmignon** [comment]
@sebastienbeau I've fixed the failure by running the tests of base_jsonify alone...

**Comment by sebastienbeau** [comment]
Ok for me. Thanks !

**Pull request merged**
